name: Build Kubelinux Base OS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/kubelinux-io/bootstrap-container:main
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Cached Kubelinux Source
        id: restore-kubelinux-source
        uses: actions/cache/restore@v4
        with:
          path: |
            sources
          key: kubelinux-source

      - name: Download Kubelinux Source
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/sources
          if wget --input-file=wget-list --continue --directory-prefix=${GITHUB_WORKSPACE}/sources; then
            echo -ne "0" > /tmp/wget_status
          else
            echo -ne "1" > /tmp/wget_status
          fi

      - name: Cache Kubelinux Source
        id: cache-kubelinux-source
        uses: actions/cache/save@v4
        with:
          path: |
            sources
          key: ${{ steps.restore-kubelinux-source.outputs.cache-primary-key }}
      
      - name: Source Code Failure Exit
        run: |
          exit $(cat /tmp/wget_status)

      - name: Prepare Binutils
        run: |
          cd ${GITHUB_WORKSPACE}/sources && mkdir binutils
          tar -xf ${GITHUB_WORKSPACE}/sources/binutils-*.tar.xz -C binutils --strip-components=1
          cd binutils && mkdir build

      - name: Configure Binutils
        run: |
          cd ${GITHUB_WORKSPACE}/sources/binutils
          ./configure \
            --prefix=${GITHUB_WORKSPACE}/tools \
            --with-sysroot=${GITHUB_WORKSPACE}/output \
            --target=$(uname -m)-lfs-linux-gnu \
            --disable-nls \
            --disable-werror
      
      - name: Make Binutils
        run: |
          cd ${GITHUB_WORKSPACE}/sources/binutils
          make -j$(nproc)
          make install
          cd ${GITHUB_WORKSPACE} && rm -Rf ${GITHUB_WORKSPACE}/sources/binutils

      - name: Prepare GCC Build
        run: |
          cd ${GITHUB_WORKSPACE}/sources && mkdir gcc
          tar -xf ${GITHUB_WORKSPACE}/sources/gcc-*.tar.xz -C gcc --strip-components=1
          cd ${GITHUB_WORKSPACE}/sources/gcc
          mkdir -p {gmp,mpc,mpfr}
          tar -xf ${GITHUB_WORKSPACE}/sources/gmp-*.tar.xz  -C ${GITHUB_WORKSPACE}/sources/gcc/gmp  --strip-components=1
          tar -xf ${GITHUB_WORKSPACE}/sources/mpc-*.tar.gz  -C ${GITHUB_WORKSPACE}/sources/gcc/mpc  --strip-components=1
          tar -xf ${GITHUB_WORKSPACE}/sources/mpfr-*.tar.xz -C ${GITHUB_WORKSPACE}/sources/gcc/mpfr --strip-components=1
          mkdir -v build
        
      - name: Configure GCC
        run: |
          cd ${GITHUB_WORKSPACE}/sources/gcc
          ./configure \
            --target=$(uname -m)-lfs-linux-gnu \
            --prefix=${GITHUB_WORKSPACE}/tools \
            --with-glibc-version=2.38 \
            --with-sysroot=${GITHUB_WORKSPACE}/output \
            --with-newlib \
            --without-headers \
            --enable-initfini-array \
            --disable-nls \
            --disable-shared \
            --disable-multilib \
            --disable-decimal-float \
            --disable-threads \
            --disable-libatomic \
            --disable-libgomp \
            --disable-libquadmath \
            --disable-libssp \
            --disable-libvtv \
            --disable-libstdcxx \
            --enable-languages=c,c++
      
      - name: Make GCC
        run: |
          cd ${GITHUB_WORKSPACE}/sources/gcc
          make -j$(nproc)
          make install
          cd ${GITHUB_WORKSPACE} && rm -Rf ${GITHUB_WORKSPACE}/sources/gcc
          

      #- name: Create OSTree Repository
      #  run: |
      #    mkdir -p /tmp/ostree_repo
      #    ostree --repo=/tmp/ostree_repo init --mode=archive-z2
      #    ostree --repo=/tmp/ostree_repo commit -b kubelinux --tree=dir=/mnt/lfs --subject="LFS Build $(date)"

      #- name: Upload OSTree Commit to S3
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #  run: |
      #    aws s3 sync /tmp/ostree_repo s3://kubelinux-ostree --acl public-read

      #- name: Publish OSTree Image as OCI for BootC
      #  run: |
      #    podman build -t ghcr.io/${{ github.repository }}/kubelinux-lfs:latest -f Dockerfile
      #    podman push ghcr.io/${{ github.repository }}/kubelinux-lfs:latest