name: Build LFS Base OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: rockylinux:9
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          dnf install -y make gcc g++ perl python3 info wget bison flex patch tar xz

      - name: Prepare LFS Build Environment
        run: |
          export LFS=/mnt/lfs
          mkdir -p $LFS
          echo "export LFS=/mnt/lfs" >> ~/.bashrc
          source ~/.bashrc

      - name: Restore Cached LFS Packages
        id: cache-lfs-packages-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /mnt/lfs
          key: lfs-package-cache

      - name: Download LFS Packages
        run: |
          wget --input-file=wget-list --continue --directory-prefix=$LFS/sources

      - name: Save Cached LFS Packages
        id: cache-lfs-packages-save
        uses: actions/cache/save@v4
        with:
          path: |
            /mnt/lfs
          key: lfs-package-cache

      - name: Build LFS System
        run: |
          cp build/build-* ${LFS}/
          chmod +x ${LFS}/build-*
          cd build
          bash build-lfs.sh

      #- name: Create OSTree Repository
      #  run: |
      #    mkdir -p /tmp/ostree_repo
      #    ostree --repo=/tmp/ostree_repo init --mode=archive-z2
      #    ostree --repo=/tmp/ostree_repo commit -b kubelinux --tree=dir=/mnt/lfs --subject="LFS Build $(date)"

      #- name: Upload OSTree Commit to S3
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #  run: |
      #    aws s3 sync /tmp/ostree_repo s3://kubelinux-ostree --acl public-read

      #- name: Publish OSTree Image as OCI for BootC
      #  run: |
      #    podman build -t ghcr.io/${{ github.repository }}/kubelinux-lfs:latest -f Dockerfile
      #    podman push ghcr.io/${{ github.repository }}/kubelinux-lfs:latest